name: Gitflow push to a branch

# on:
#   push:

on:
  workflow_call:
  
jobs:
  process-push:
    name: Process push to a Gitflow branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine branch type
        id: branch_type
        run: |
          if [[ ${GITHUB_REF_NAME} == main ]] ; then
            echo "value=main" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == develop ]] ; then
            echo "value=develop" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == release* ]] ; then
            echo "value=release" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == hotfix* ]] ; then
            echo "value=hotfix" >> $GITHUB_OUTPUT
          else
            echo "value=feature" >> $GITHUB_OUTPUT
          fi
      - name: Push to main
        if: steps.branch_type.outputs.value == 'main'
        uses: ./.github/workflows/gitflow_main_on_push.yml
      - name: Push to release
        if: steps.branch_type.outputs.value == 'release'
        uses: ./.github/workflows/gitflow_release_on_push.yml
      - name: Push to hotfix
        if: steps.branch_type.outputs.value == 'hotfix'
        uses: ./.github/workflows/gitflow_hotfix_on_push.yml
      - name: Push to feature
        if: steps.branch_type.outputs.value == 'feature'
        uses: ./.github/workflows/gitflow_feature_on_push.yml
        