name: Push to branch

on:
  push:

jobs:
  process-push:
    name: Execute push on branch
    runs-on: ubuntu-latest
    permissions:
      contents: write # this must be set to 'write' in order for the workflow to add a tag
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine branch type
        id: branch_type
        run: |
          if [[ ${GITHUB_REF_NAME} == main* ]]; then
            echo "value=main" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == hotfix* ]]; then
            echo "value=hotfix" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == release* ]]; then
            echo "value=release" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == develop* ]]; then
            echo "value=develop" >> $GITHUB_OUTPUT
          else
            echo "value=feature" >> $GITHUB_OUTPUT
          fi
      - name: Push to main
        run: echo This is a push to main
      - name: Push to hotfix
        run: echo This is a push to hotfix
      - name: Push to release
        run: echo This is a push to release
      - name: Push to develop
        run: echo This is a push to develop
      - name: Push to feature
        run: echo This is a push to feature

  