name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  process-push:
    name: Execute push on main
    runs-on: ubuntu-latest
    permissions:
      contents: write # this must be set to 'write' in order for the workflow to add a tag
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine release version value
        id: release_version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Show the release version value
        run: 'echo This is the release version that any job or step in the workflow can now use: ${{steps.release_version.outputs.value}}'
      - name: Tag the branch with the application version
        uses: rickstaa/action-create-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{steps.release_version.outputs.value}}
      - name: Build
        run: echo This is the build step
      - name: Static Application Security Testing (SAST) 
        run: echo This is the SAST step
      - name: Software Composition Analysis (SCA)
        run: echo This is the SCA step
      - name: SyStem Integration testing (SIT)
        run: echo This is the SIT step
      - name: Dynamic Application Security Testing (DAST) 
        run: echo This is the DAST step
      - name: Performance Test (PT) 
        run: echo This is the DAST step  