name: Push to feature branch

on:
  workflow_call:

jobs:
  process-push:
    name: Execute push on feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine feature tag value
        id: determine_version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Create a tag for the feature
        id: feature_tag
        run: echo "value=${{ steps.determine_version.outputs.version_tag }}+${{ steps.determine_version.outputs.increment }}-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Show the feature tag value
        run: 'echo This is the feature tag value that any job or step in the workflow can now use: ${{steps.feature_tag.outputs.value}}'
